// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"simple-chat-app/server/src/repos"
	"simple-chat-app/server/src/routers"
	"simple-chat-app/server/src/services"
	"simple-chat-app/server/src/shared"
	"simple-chat-app/server/src/util"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	envVars := shared.NewEnvVars()
	jwtUtil := util.NewJwtUtil(envVars)
	db := getDbConn(envVars)
	userRepo := repos.NewUserRepo(db)
	pwdUtil := util.NewPwdUtil()
	authService := services.NewAuthService(userRepo, pwdUtil)
	authRouter := routers.NewAuthRouter(envVars, jwtUtil, authService)
	userService := services.NewUserService(userRepo, pwdUtil)
	userRouter := routers.NewUserRouter(userService)
	apiRouter := routers.NewApiRouter(authRouter, userRouter)
	middlware := routers.NewMiddleware(envVars, jwtUtil)
	server := NewServer(envVars, apiRouter, middlware)
	return server, nil
}
